[programs.localnet]
monocle_program_v2 = "7mhd1er7u7fuitb6KkE38CNmmBsU5nXK8nBu2ff1jsUn"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/nidza/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/home/nidza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
