[programs.localnet]
monocle_program_v2 = "3gMPeFzLCg8sXeAWWr55cd8hDxTEVcHV7yLf5FgsZNHa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nidza/.config/solana/id.json"

#[provider]
#cluster = "devnet"
#wallet = "/home/nidza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
